app = "character-vitae"

[build]
  dockerfile = "docker/Dockerfile.prod"

[env]
  APP_ENV = "prod"
  APP_DEBUG = "0"

# Tell fly this is an HTTP service on internal_port 8080
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false   # temporaire pour debug
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # optional healthcheck for the proxy to know instance is healthy
  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/_health"         # <--- utiliser /_health (ton nginx le sert)
    protocol = "http"
    grace_period = "30s"      # laisse un peu plus de marge au dÃ©marrage
    restart_limit = 0
